name: Deploy Medusa on ECS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push Docker image
        run: |
          IMAGE_URI=123456789012.dkr.ecr.us-east-1.amazonaws.com/medusa-backend:latest
          docker build -t $IMAGE_URI .
          docker push $IMAGE_URI

      - name: Terraform deploy
        working-directory: terraform
        run: |
          terraform init
          terraform apply -auto-approve

